---
title: Replication of Study 1 by Song & Schwartz (2008, Social Cognition)
author: Jae Kwon
date: "`r format(Sys.time(), '%B %d, %Y')`"
format:
  html:
    toc: true
    toc_depth: 3
---

<!-- Replication reports should all use this template to standardize reporting across projects.  These reports will be public supplementary materials that accompany the summary report(s) of the aggregate results. -->

## Introduction

The chosen research article pertains to my research interests extensively. First,
my research background up to this point has been on the illusory truth effect, where
repetition increases belief, and this occurs because processing fluency is facilitated 
during the process. People often rely on their heuristics, such as fluency, to make
numerous decisions. Additionally, people often mistakenly think whatever is retrieved/processed
faster is more true or legitimate. Hence, I believe basic mechanisms such as fluency is important to understand given the consequences of our behavior. The results of this experiment is promising
because if we interrupt our initial quick-and-easy processing fluency, it leaves room for us to
use our prior knowledge and make sounder decisions. Finally, given my current research interests
in misinformation and how people's beliefs are formed and corrected, understanding fluency
and its influence on belief will be useful.

In order to replicate the experiment, we will need a couple of trivia statements to use.
After establishing the trivia statements, we would need to manipulate the processing fluency
through choosing an 'easy to read' font and 'hard to read' font. We would need to pretest the fonts
to ensure that participants find them easy and difficult enough. Then, participants would be
randomly assigned to the 'easy' condition and 'hard condition,' where they would answer
the trivia statements. Finally, we would compare their error rates on the Moses illusion.
We will be using Qualtrics to build and distribute the survey.

I believe this is a pretty straightforward experiment, where I don't anticipate too many
challenges (at least I hope!), especially given how robust the basic fluency effects are (e.g., there's research showing that facilitated fluency leads to increased belief even for
implausible statements). Although, one challenge I do anticipate is that the Moses illusion
example may not be as familiar to the younger generation (which could be our sample),
where they don't know what the correct or incorrect answer is.


## Methods

### Power Analysis

Original effect size, power analysis for samples to achieve 80%, 90%, 95% power to detect that effect size.  Considerations of feasibility for selecting planned sample size.

### Planned Sample

Planned sample size and/or termination rule, sampling frame, known demographics if any, preselection rules if any.

### Materials

All materials - can quote directly from original article - just put the text in quotations and note that this was followed precisely.  Or, quote directly and just point out exceptions to what was described in the original article.

### Procedure	

Can quote directly from original article - just put the text in quotations and note that this was followed precisely.  Or, quote directly and just point out exceptions to what was described in the original article.

### Analysis Plan

Can also quote directly, though it is less often spelled out effectively for an analysis strategy section.  The key is to report an analysis strategy that is as close to the original - data cleaning rules, data exclusion rules, covariates, etc. - as possible.  

**Clarify key analysis of interest here**  You can also pre-specify additional analyses you plan to do.

### Differences from Original Study

Explicitly describe known differences in sample, setting, procedure, and analysis plan from original study.  The goal, of course, is to minimize those differences, but differences will inevitably occur.  Also, note whether such differences are anticipated to make a difference based on claims in the original article or subsequent published research on the conditions for obtaining the effect.

### Methods Addendum (Post Data Collection)

You can comment this section out prior to final report with data collection.

#### Actual Sample
  Sample size, demographics, data exclusions based on rules spelled out in analysis plan

#### Differences from pre-data collection methods plan
  Any differences from what was described as the original plan, or “none”.


## Results


### Data preparation

Data preparation following the analysis plan.
	
```{r include=F}
### Data Preparation

#### Load Relevant Libraries and Functions

#### Import data

#### Data exclusion / filtering

#### Prepare data for analysis - create columns etc.
```

### Confirmatory analysis

The analyses as specified in the analysis plan.  

*Side-by-side graph with original graph is ideal here*

### Exploratory analyses

Any follow-up analyses desired (not required).  

## Discussion

### Summary of Replication Attempt

Open the discussion section with a paragraph summarizing the primary result from the confirmatory analysis and the assessment of whether it replicated, partially replicated, or failed to replicate the original result.  

### Commentary

Add open-ended commentary (if any) reflecting (a) insights from follow-up exploratory analysis, (b) assessment of the meaning of the replication (or not) - e.g., for a failure to replicate, are the differences between original and present study ones that definitely, plausibly, or are unlikely to have been moderators of the result, and (c) discussion of any objections or challenges raised by the current and original authors about the replication attempt.  None of these need to be long.
